from typing import Literal

# Type Aliases for static type checking
RunOptions = Literal['ENABLE', 'DISABLE']
ValidUnits = Literal["INCH", "MILLIMETER", "OTHER", "FEET", "MILE", "METER", "KILOMETER", "MILS", "MICRON", "CENTIMETER", "MICROINCH"]
ValidForceUnits = Literal['COEFFICIENTS', 'NEWTONS', 'KILO-NEWTONS', 'POUND-FORCE', 'KILOGRAM-FORCE']
ValidPlanes = Literal['XY', 'XZ', 'YZ']
BaseRegionType = Literal['EMPIRICAL', 'CONSTANT']
ValidDimensions = Literal['2D', '3D']
ValidAxis = Literal['X', 'Y', 'Z']
ValidGrowthScheme = Literal[1, 2, 3, 4]
ValidSymmetry = Literal['XY', 'XZ', 'YZ', 'NONE']
ValidCadMesh = Literal['CAD', 'MESH']
ValidQuadrant = Literal[1, 2, 3, 4]
ValidRotationAxis = Literal['X', 'Y', 'Z', '1', '2', '3']
ValidExportFormat = Literal['CP-FREESTREAM', 'CP-REFERENCE', 'PRESSURE']
ValidPressureUnits = Literal['PASCALS', 'MEGAPASCALS', 'BAR', 'ATMOSPHERES', 'PSI']
ValidFreestreamType = Literal['CONSTANT', 'CUSTOM', 'ROTATION']

# Lists for runtime validation
VALID_RUN_OPTIONS = ['ENABLE', 'DISABLE']
VALID_UNITS_LIST = ["INCH", "MILLIMETER", "OTHER", "FEET", "MILE", "METER", "KILOMETER", "MILS", "MICRON", "CENTIMETER", "MICROINCH"]
VALID_FORCE_UNITS_LIST = ['COEFFICIENTS', 'NEWTONS', 'KILO-NEWTONS', 'POUND-FORCE', 'KILOGRAM-FORCE']
VALID_PLANE_LIST = ['XY', 'XZ', 'YZ']
VALID_BASE_REGION_TYPE_LIST = ['EMPIRICAL', 'CONSTANT']
VALID_DIMENSIONS_LIST = ['2D', '3D']
VALID_AXIS_LIST = ['X', 'Y', 'Z']
VALID_GROWTH_SCHEME_LIST = [1, 2, 3, 4]
VALID_SYMMETRY_LIST = ['XY', 'XZ', 'YZ', 'NONE']
VALID_CAD_MESH_LIST = ['CAD', 'MESH']
VALID_QUADRANT_LIST = [1, 2, 3, 4]
VALID_ROTATION_AXIS_LIST = ['X', 'Y', 'Z', '1', '2', '3']
VALID_EXPORT_FORMAT_LIST = ['CP-FREESTREAM', 'CP-REFERENCE', 'PRESSURE']
VALID_PRESSURE_UNITS_LIST = ['PASCALS', 'MEGAPASCALS', 'BAR', 'ATMOSPHERES', 'PSI']
VALID_FREESTREAM_TYPE_LIST = ['CONSTANT', 'CUSTOM', 'ROTATION']
